name: iOS Workflow

on:
    pull_request:
        branches: ["main"]

jobs:
    build:
        name: Build default scheme using any available iPhone simulator
        runs-on: macos-latest

        steps:
            - name: Clean build the project
              run: xcodebuild clean
            - name: Build the project
              run: xcodebuild build -scheme "E-Buddy" -sdk iphoneos -destination generic/platform=iOS -allowProvisioningUpdates